`timescale 1ns/1ps
interface cam_vga_if(input logic clk, input logic pclk);
    logic rst_n = 0;
    logic cam_href = 0, cam_vsync = 0;
    logic [7:0] cam_data = 0;
    bit check_camera = 0, check_vga = 0, check_sccb = 0;
    bit link_camera_to_vga = 0;
    int camera_phase_ns = 0;
    logic sccb_start = 0;
    logic mem_we = 0;
    logic [16:0] mem_addr = 0;
    logic [15:0] mem_data = 0;
    logic setup_busy, setup_done, setup_error, cam_scl, xclk;
    tri1 cam_sda;
    logic sccb_ack_low = 0;
    assign cam_sda = sccb_ack_low ? 1'b0 : 1'bz;
    logic h_sync, v_sync;
    logic [11:0] rgb;
    logic cap_we;
    logic [16:0] cap_addr, rd_addr;
    logic [15:0] cap_data, rd_data;
    logic de;
    logic [9:0] x, y;
    int pattern_id = 0;
    bit capture_complete = 0;
    int nack_transaction = -1, nack_byte = -1;
    int cfg_freq_hz = 1000000, sccb_freq_hz = 100000;
    int sccb_epoch = 0;
    logic [3:0] sccb_master_state;
    logic [1:0] sccb_master_step;
    logic [2:0] sccb_setup_state;
endinterface
