`timescale 1ns / 1ps

// =================================================================================
// Module: OV7670_top
// Purpose: Top-level module for the OV7670 camera system.
//          - Handles UART communication and control signals.
//          - Captures camera pixels, applies zoom and video filters.
//          - Overlays screen UI elements (borders, label).
//          - Sends final 12-bit RGB video to VGA output.
// Data Flow:
//   UART Link -> Video Processing Path -> UI Overlay -> Output Registers -> VGA Pins
// =================================================================================

module OV7670_top #(
    parameter integer CLK_FREQ_HZ = 100_000_000, // System clock frequency (100 MHz)
    parameter integer BAUD_RATE   = 115200      // UART communication speed
) (
    input  logic       clk,
    input  logic       rst_n,

    // ============================================================
    // UART Interface (Communicates with tracking board)
    // ============================================================
    input  logic       uart_rx,      // UART receive line
    output logic       uart_tx,      // UART transmit line

    // ============================================================
    // OV7670 Camera Hardware Interface
    // ============================================================
    input  logic       pclk,         // Pixel clock generated by camera hardware
    input  logic       cam_href,     // Horizontal reference signal (active high line data)
    input  logic       cam_vsync,    // Vertical sync signal (active high frame start)
    input  logic [7:0] cam_data,     // 8-bit camera pixel data input
    output logic       xclk,         // Master clock output sent to camera (24/25 MHz)

    // ============================================================
    // Camera Configuration (SCCB / I2C Interface)
    // ============================================================
    output logic       setup_busy,   // High while sending camera configuration settings
    output logic       setup_done,   // High when camera configuration is complete
    output logic       setup_error,  // High if camera communication fails
    output logic       cam_scl,      // SCCB clock line
    inout  wire        cam_sda,      // SCCB data line (bidirectional)

    output logic       unlock_en,    // System unlock status output from UART link

    // ============================================================
    // VGA Physical Output Interface
    // ============================================================
    output logic       h_sync,       // VGA horizontal synchronization pulse
    output logic       v_sync,       // VGA vertical synchronization pulse
    output logic [3:0] port_red,     // 4-bit VGA Red channel
    output logic [3:0] port_green,   // 4-bit VGA Green channel
    output logic [3:0] port_blue     // 4-bit VGA Blue channel
);

    // ============================================================
    // Sub-module 1: UART Link Block
    // Handles command reception, 10-second timeout, and signal decoding
    // ============================================================
    logic zoom_en;                   // Enable digital zoom mode
    logic effect_sel;                // Select video effect / filter mode
    logic btn_l, btn_r, btn_d;       // Button inputs: Left, Right, Down
    logic btn_u_pulse;               // Single-clock pulse for Up button

    uart_link #(
        .CLK_FREQ_HZ(CLK_FREQ_HZ),
        .BAUD_RATE  (BAUD_RATE)
    ) U_UART_LINK (
        .clk        (clk),
        .rst_n      (rst_n),
        .rx         (uart_rx),
        .tx         (uart_tx),
        .zoom_en    (zoom_en),
        .effect_sel (effect_sel),
        .btn_l      (btn_l),
        .btn_r      (btn_r),
        .btn_d      (btn_d),
        .btn_u_pulse(btn_u_pulse),
        .unlock_en  (unlock_en)
    );

    // ============================================================
    // Sub-module 2: Video Processing Path
    // Includes SCCB setup, pixel capture, frame buffer, zoom, and filters
    // ============================================================
    logic        vp_h_sync;          // Intermediate horizontal sync signal
    logic        vp_v_sync;          // Intermediate vertical sync signal
    logic [11:0] vp_rgb;             // Intermediate 12-bit RGB color data
    logic [3:0]  filter_id;           // Current filter state for HUD

    video_path U_VIDEO_PATH (
        .clk        (clk),
        .pclk       (pclk),          // Direct camera pixel clock input
        .rst_n      (rst_n),
        .unlock_en  (unlock_en),
        .zoom_en    (zoom_en),
        .effect_sel (effect_sel),
        .btn_l      (btn_l),
        .btn_r      (btn_r),
        .btn_d      (btn_d),
        .btn_u      (btn_u_pulse),
        .cam_href   (cam_href),
        .cam_vsync  (cam_vsync),
        .cam_data   (cam_data),
        .xclk       (xclk),
        .setup_busy (setup_busy),
        .setup_done (setup_done),
        .setup_error(setup_error),
        .cam_scl    (cam_scl),
        .cam_sda    (cam_sda),
        .o_h_sync   (vp_h_sync),
        .o_v_sync   (vp_v_sync),
        .o_rgb      (vp_rgb),
        .o_filter_id(filter_id)
    );

    // ============================================================
    // Sub-module 3: User Interface Overlay
    // Adds the Home Cam HUD, privacy state, and live filter/zoom status
    // ============================================================
    logic        ui_h_sync;          // UI-processed horizontal sync signal
    logic        ui_v_sync;          // UI-processed vertical sync signal
    logic [11:0] ui_rgb;             // UI-processed RGB color data
    ui_frame_wrapper U_UI (
        .clk         (clk),
        .rst_n       (rst_n),
        .i_h_sync    (vp_h_sync),
        .i_v_sync    (vp_v_sync),
        .i_rgb       (vp_rgb),
        .i_unlock_en (unlock_en),
        .i_zoom_en   (zoom_en),
        .i_filter_id (filter_id),
        .o_h_sync    (ui_h_sync),
        .o_v_sync    (ui_v_sync),
        .o_rgb       (ui_rgb)
    );

    // ============================================================
    // Sub-module 4: VGA Output Register Block
    // Registers sync and color signals for stable timing output
    // ============================================================
    logic [11:0] out_rgb;

    vga_outreg U_VGA_OUTREG (
        .clk     (clk),
        .rst_n   (rst_n),
        .i_h_sync(ui_h_sync),
        .i_v_sync(ui_v_sync),
        .i_rgb   (ui_rgb),
        .o_h_sync(h_sync),
        .o_v_sync(v_sync),
        .o_rgb   (out_rgb)
    );

    // Split 12-bit RGB signal into 4-bit Red, 4-bit Green, and 4-bit Blue physical pins
    assign {port_red, port_green, port_blue} = out_rgb;

endmodule
